def key_libs():
    list = {
        '':'',
        'Backspace': 'backspace',
        'Tab': 'tab',
        'Enter': 'enter',
        'Shift': 'shift',
        'Ctrl': 'ctrl',
        'Alt': 'alt',
        'Caps_Lock': 'caps lock',
        'Esc': 'esc',
        'Spacebar': 'spacebar',
        'Page_Up': 'page up',
        'Page_Down': 'page down',
        'End': 'end',
        'Home': 'home',
        'Left': 'left',
        'Up': 'up',
        'Right': 'right',
        'Down': 'down',
        'Select': 'select',
        'Print_Screen': 'print screen',
        'Insert': 'insert',
        'Delete': 'delete',
        '0': '0',
        '1': '1',
        '2': '2',
        '3': '3',
        '4': '4',
        '5': '5',
        '6': '6',
        '7': '7',
        '8': '8',
        '9': '9',
        'a': 'a',
        'b': 'b',
        'c': 'c',
        'd': 'd',
        'e': 'e',
        'f': 'f',
        'g': 'g',
        'h': 'h',
        'i': 'i',
        'j': 'j',
        'k': 'k',
        'l': 'l',
        'm': 'm',
        'n': 'n',
        'o': 'o',
        'p': 'p',
        'q': 'q',
        'r': 'r',
        's': 's',
        't': 't',
        'u': 'u',
        'v': 'v',
        'w': 'w',
        'x': 'x',
        'y': 'y',
        'z': 'z',
        'Left_Windows': 'left windows',
        'Right_Windows': 'right windows',
        '*': '*',
        '+': '+',
        '-': '-',
        '/': '/',
        'F1': 'f1',
        'F2': 'f2',
        'F3': 'f3',
        'F4': 'f4',
        'F5': 'f5',
        'F6': 'f6',
        'F7': 'f7',
        'F8': 'f8',
        'F9': 'f9',
        'F10': 'f10',
        'F11': 'f11',
        'F12': 'f12',
        'Left_Shift': 'left shift',
        'Right_Shift': 'right shift',
        'Left_Ctrl': 'left ctrl',
        'Right_Ctrl': 'right ctrl',
        'Browser_Back': 'browser back',
        'Browser_Forward': 'browser forward',
        'Browser_Refresh': 'browser refresh',
        'Browser_Stop': 'browser stop',
        'Browser_Favorites': 'browser favorites',
        'Volume_Mute': 'volume mute',
        'Volume_Down': 'volume down',
        'Volume_Up': 'volume up',
        'Next_Track': 'next track',
        'Previous_Track': 'previous track',
        'Stop_Media': 'stop media',
        'Play/Pause_Media': 'play/pause media',
    }
    return list

if __name__ == '__main__':
    pass